### ISSUE TITLE
Cant launch the converter

### ISSUE THREAD

**Issue by SoOriginalWow** [accountrev/funkychart#1]
Cant launch it because of ModuleNotFoundError: No module named 'colorama'
Even though i already installed it
Traceback (most recent call last):
  File "FunkyChartConverter.py", line 58, in <module>
ModuleNotFoundError: No module named 'colorama'
[1104] Failed to execute script 'FunkyChartConverter' due to unhandled exception!

**Comment by accountrev** [comment]
> Cant launch it because of ModuleNotFoundError: No module named 'colorama'
> Even though i already installed it
> Traceback (most recent call last):
> File "FunkyChartConverter.py", line 58, in 
> ModuleNotFoundError: No module named 'colorama'
> [1104] Failed to execute script 'FunkyChartConverter' due to unhandled exception!

Hey, thanks for reporting. Is this an issue with the executable file that is available to download or the actual Python source code itself?

**Comment by SoOriginalWow** [comment]
> > Cant launch it because of ModuleNotFoundError: No module named 'colorama'
> > Even though i already installed it
> > Traceback (most recent call last):
> > File "FunkyChartConverter.py", line 58, in
> > ModuleNotFoundError: No module named 'colorama'
> > [1104] Failed to execute script 'FunkyChartConverter' due to unhandled exception!
> 
> Hey, thanks for reporting. Is this an issue with the executable file that is available to download or the actual Python source code itself?
I dont really know if it's issue with python or executable file, but if i already have colorama installed that's probably issue with the executable file.

**Comment by accountrev** [comment]
> > > Cant launch it because of ModuleNotFoundError: No module named 'colorama'
> > > Even though i already installed it
> > > Traceback (most recent call last):
> > > File "FunkyChartConverter.py", line 58, in
> > > ModuleNotFoundError: No module named 'colorama'
> > > [1104] Failed to execute script 'FunkyChartConverter' due to unhandled exception!
> > 
> > 
> > Hey, thanks for reporting. Is this an issue with the executable file that is available to download or the actual Python source code itself?
> > I dont really know if it's issue with python or executable file, but if i already have colorama installed that's probably issue with the executable file.

Don't worry, the issue has been fixed! Check the latest release.
