### ISSUE TITLE
ERROR 268

### ISSUE THREAD

**Issue by Gavin123-code** [accountrev/funkychart#10]
so i tried to use the thing and then i could not join even in other games i just got error 268 essentially i cant join any game HELP PLEASE I CANT PLAY ROBLOX AT ALL

**Comment by accountrev** [comment]
That's not my issue, that's an issue on your end or Roblox's end. I have nothing to do with it.

**Comment by Gavin123-code** [comment]
> That's not my issue, that's an issue on your end or Roblox's end. I have nothing to do with it.

I didnt know
