### ISSUE TITLE
Attempt to call a nil value

### ISSUE THREAD

**Issue by SnivyFan11** [accountrev/funkychart#12]
So im trying to load a song i converted, but when i click "Load Chart", It gives me a error saying something like "An oopsie occurred [Insert random numbers and letters] attempt to call a nil value", Anyway to fix this? (also before you ask, yes, everything is where it should be, like the chart and audio for the song is in the funkychart folder in the synapse x workspace folder, and that synapse is my selected executor)
![no](https://user-images.githubusercontent.com/103345062/162599230-c61e9d26-064b-4de7-a278-7262d54a4e3c.png)

**Comment by vurgry** [comment]
![image](https://user-images.githubusercontent.com/103345746/162599810-133e3bdd-43f4-40cd-921d-a34ea41ee317.png)
same for me, with everything in its place as well. i even tried restarting the whole process, no success

**Comment by accountrev** [comment]
I found the problem before this issue was created, but I'll have make you guys wait until 1.1. Thanks for reporting this though!
