### ISSUE TITLE
I can't click more than 2 notes

### ISSUE THREAD

**Issue by Reanimga** [accountrev/funkychart#13]
So, whenever I try to do 3 notes or 4 notes at the same time, it only registers as me doing 2 notes at the same time

**Comment by accountrev** [comment]
Not sure what you mean by this. Can you tell me more details?

**Comment by accountrev** [comment]
Actually, do you play with arrow keys?

**Comment by accountrev** [comment]
Check out new update
https://github.com/accountrev/funkychart/releases/latest
