### ISSUE TITLE
No funky chart appears in the krnl files in workspace

### ISSUE THREAD

**Issue by Errorsansiguess** [accountrev/funkychart#14]
![image](https://user-images.githubusercontent.com/87914239/162619596-49ed5946-ed1e-4d2d-bbbc-1efed523d65b.png)
I have tried adding a new file and I loaded the script and it hasn't appeared at all

**Comment by accountrev** [comment]
Are you loading the script that comes with the download?

**Comment by Errorsansiguess** [comment]
yes i am

**Comment by accountrev** [comment]
https://github.com/accountrev/funkychart/releases/latest
Try the latest version out
