### ISSUE TITLE
Error...

### ISSUE THREAD

**Issue by TechHopGitHub** [accountrev/funkychart#19]
When I click it to load i get this error:
**An Oopsie Occured!**
:152: attempt to call a nil value
Please report this!
 
Can someone help me?

Here is a screenshot:
![Screenshot](https://user-images.githubusercontent.com/82542226/162854622-b4e52cf3-5268-4919-ba35-a219bad857fe.png)

**Comment by accountrev** [comment]
https://github.com/accountrev/funkychart/releases/latest
New update, you'll need to re-convert your chart as it uses a new system.

**Comment by TechHopGitHub** [comment]
oh this happened 4 minutes before oops
