### ISSUE TITLE
I can't play the chart because "No Audio"

### ISSUE THREAD

**Issue by TPLTruong** [accountrev/funkychart#20]
I have the proper things in the workspace folder with the chart and the audio. I'm using krnl I think when I'm using the option to load a chart it doesn't load idk why I have everything converted already.

**Comment by accountrev** [comment]
Can you send screenshots of your Charts and Audio folder?

**Comment by TPLTruong** [comment]
![Capture](https://user-images.githubusercontent.com/103491506/163362115-d1e51370-988b-4139-99a1-1f14800b3a28.PNG)
![Capture1](https://user-images.githubusercontent.com/103491506/163362123-e0ac0109-2926-43e7-869c-f4efe5245d45.PNG)
So I have everything like it should. Although I don't see why it wouldn't work.

**Comment by accountrev** [comment]
Check out the new update
https://github.com/accountrev/funkychart/releases/latest
