### ISSUE TITLE
 The chart doesn't load correctly?

### ISSUE THREAD

**Issue by Y0ICHI** [accountrev/funkychart#21]
When I try to load the chart it tells me that it finds it but then it gets stuck without doing anything
![image](https://user-images.githubusercontent.com/90846439/162986236-5a5784b4-5b7c-403d-9a6d-efc0124a580b.png)

**Comment by accountrev** [comment]
Make sure the chart isn't an older version from previous versions. You need to reconvert it for 1.1

**Comment by Y0ICHI** [comment]
I reconvert whit new version and when excute the script appear this (the part of the red rectangle) but sadly still don't works
![image](https://user-images.githubusercontent.com/90846439/163113255-47a889c0-498d-484e-b678-135445d4dbf4.png)

**Comment by accountrev** [comment]
Check out the new update
https://github.com/accountrev/funkychart/releases/latest
