### ISSUE TITLE
The song timer stays in 0:00

### ISSUE THREAD

**Issue by MrMIG8** [accountrev/funkychart#22]
I think I have everything in order but the song doesn't load,
![Captura de pantalla (237)](https://user-images.githubusercontent.com/103606557/163268701-ca809a1f-0795-4348-b7ee-36302b8b932c.png)
It just stays like that no matter how long I wait

![Captura de pantalla 2022-04-13 165543](https://user-images.githubusercontent.com/103606557/163268941-af317bc3-00c9-404c-bbbd-5517e41c3d73.png)
![Captura de pantalla 2022-04-13 165529](https://user-images.githubusercontent.com/103606557/163268949-5e3acd63-7934-4eda-9c33-fad729941095.png)

I converted them with 1.1v but nothing
 I'm using krnl

**Comment by accountrev** [comment]
Check out the new update
https://github.com/accountrev/funkychart/releases/latest

**Comment by MrMIG8** [comment]
> Check out the new update https://github.com/accountrev/funkychart/releases/latest

Still doesn't work tho, even with the "DELETE SAVE" option :(

![Captura de pantalla (238)](https://user-images.githubusercontent.com/103606557/163480484-e0c5c21a-bee1-4e08-b2d8-19a5fbbfcd1d.png)
