### ISSUE TITLE
Critical Error

### ISSUE THREAD

**Issue by Lumaah** [accountrev/funkychart#33]
i got this error today when trying a new chart that i converted
i used this osu beatmap 
https://drive.google.com/file/d/1beooDzfq_8vPEAzQ5xi0hXV_gVilH4bj/view
![image](https://user-images.githubusercontent.com/89982938/178471669-21334117-9089-4f58-937f-70296fb70134.png)

**Comment by accountrev** [comment]
Hello, v1.2 just released, but to me it looks like whatever executor you have doesn't support isfile.
Try using v1.2 to see if it's fixed? What executor are you using?

**Comment by Lumaah** [comment]
I'm using KRNL i'm going to check if the 1.2 fixes this bug

**Comment by Lumaah** [comment]
oh yeah i forgot to say but i tried other charts and they worked great

**Comment by accountrev** [comment]
![image](https://user-images.githubusercontent.com/55156874/178806315-6470b574-3708-4322-a8b7-c4e8863e76aa.png)
Confirmed working on v1.2

**Comment by accountrev** [comment]
It might be a KRNL issue, I will have to check in a moment to see if it is.

**Comment by Lumaah** [comment]
Works fine with KRNL now , Thanks !

**Comment by accountrev** [comment]
Just saw it myself, thanks for reporting!
