### ISSUE TITLE
Loading chart goes black

### ISSUE THREAD

**Issue by TheRealDood** [accountrev/funkychart#35]
Whenever i load a chart, the screen goes black, but the chart plays.
![image](https://user-images.githubusercontent.com/83540641/182963009-7f439801-b109-4c15-a36f-33b7c877fb7c.png)

**Comment by accountrev** [comment]
Thanks for reporting. What executor are you using?

In the "Issues" tab, there is a toggle for "Enable Console". Re-execute FunkyChart and use it like normally.
When you get to the black screen, screenshot the console and send it here please.

**Comment by TheRealDood** [comment]
I am using synapse x, this is what the console says 
![image](https://user-images.githubusercontent.com/83540641/182970336-695deb6e-8e70-48cc-8895-3ab7eb87626e.png)

**Comment by accountrev** [comment]
Is there any errors in the executor console? You can open it with the INSERT key iirc.

**Comment by TheRealDood** [comment]
nothing in the executor console, 
![image](https://user-images.githubusercontent.com/83540641/182972532-c4561462-4955-4d3d-8544-6f794e7970f2.png)

**Comment by TheRealDood** [comment]
i also noticed that when ever that does happen, the chat lags, you can kinda see it in the screenshot

**Comment by accountrev** [comment]
There may be a good chance that the new update broke something, can you send over your chart?

**Comment by TheRealDood** [comment]
[1505323 Camellia - OOPARTS.zip](https://github.com/accountrev/funkychart/files/9264142/1505323.Camellia.-.OOPARTS.zip)
heres the chart

**Comment by accountrev** [comment]
It seems to be working on my end. Do you have the Underframe feature enabled?
![image](https://user-images.githubusercontent.com/55156874/182975355-3810d174-58d7-4822-a90b-e7b6285510d6.png)

**Comment by TheRealDood** [comment]
here is that one, it does the same on both charts.
[628571 Camellia - ANOMALY.zip](https://github.com/accountrev/funkychart/files/9264241/628571.Camellia.-.ANOMALY.zip)

**Comment by accountrev** [comment]
This one also looks fine. Weird.
![image](https://user-images.githubusercontent.com/55156874/182976456-f321443f-19eb-49d4-ad6a-d70612cb7166.png)

**Comment by accountrev** [comment]
This may be a bit difficult, but could you tell me some of the settings you have enabled/disabled on Funky Friday?
Also to answer my previous question, do you have the Underframe feature enabled?

**Comment by TheRealDood** [comment]
here is a video of my settings, and the Underframe settings is disabled
https://streamable.com/7ot8ax

**Comment by TheRealDood** [comment]
ok so i believe i know what the problem is, the option "Prevent Error Spam Lag", it works when toggled on but it doesnt toggled off

**Comment by accountrev** [comment]
Will look into this tomorrow.
Also the chat being slow is just Roblox as of right now.

https://twitter.com/roblox_rtc/status/1555346404876460032

**Comment by accountrev** [comment]
Found the issue.
Looks like Lyte Interactive changed how stages work, and now softlocks the game if you start a chart outside of a stage.

The solution to this is to make the "Prevent Error Spam Lag" permanently enabled. In previous updates, the game would spam the console with a lot of errors when outside of a stage, causing FPS drops. That's why this can be enabled/disabled.

Your settings are fine, and it's just another update that broke the script entirely.

Thanks for reporting!

**Comment by accountrev** [comment]
Also, the script has been updated with this fix.
