### ISSUE TITLE
Songs won't work

### ISSUE THREAD

**Issue by Burned38** [accountrev/funkychart#36]
It only teleports me to the stage and the song says 0:00.

**Comment by jsdrgjhsadrt** [comment]
same bro :(

**Comment by jsdrgjhsadrt** [comment]
lets just hope someone sees this and proceeds to help

**Comment by accountrev** [comment]
This is currently an issue with the Krnl executor that I can't fix. I will try to find an alternative in the meantime.

**Comment by accountrev** [comment]
Please check out v1.22 to see if this is fixed.
