### ISSUE TITLE
GUI loading permenantly.

### ISSUE THREAD

**Issue by anonymoustwo2** [accountrev/funkychart#38]
Hello.
I've encountered an issue where, upon executing the script, the GUI **loads forever.**
Upon first getting this script and using it, it loaded just fine. Prior to loading any charts, or even interacting with the UI, I closed Roblox to join a different private server. When I had joined the new one, I re-executed the script, and it was stuck in a loading state. This issue persists throughout every private server I have joined. 
![image](https://user-images.githubusercontent.com/112734298/188245110-d855f9e4-dcac-43a2-a431-11db578c76fd.png)

**Comment by anonymoustwo2** [comment]
Update: I've tried using it on a different account, and the issue still occurs.

**Comment by accountrev** [comment]
Hello, I have tried to replicate the problem you are having right now, but I'm having no luck.

Could you take screenshots of BOTH the Roblox console (press F9 to open it) whenever this error happens? Could you also send over a log file from the GUI console as well (press the Minus key to open it, and press on the SAVE button. The log file should be saved in your executor's workspace folder)?

**Comment by accountrev** [comment]
Will be releasing a new update, please check if this is fixed whenever I do upload the update.
