### ISSUE TITLE
Down note is not being converted

### ISSUE THREAD

**Issue by Lumaah** [accountrev/funkychart#39]
The down note doesn't get converted each time i convert the beatmap
![image](https://user-images.githubusercontent.com/89982938/189492797-e4bd19b0-b125-41e1-8618-3b461d243003.png)
![screenshot003](https://user-images.githubusercontent.com/89982938/189492809-880f2842-2314-47d3-b9bf-b4f8f508edf3.jpg)

**Comment by accountrev** [comment]
Hello, this is probably a beatmap issue, with the down note being at the wrong offset. To combat this, the converter just outright removes the note that it has issues with.

Can you please send the .osu file here? I would like to take a look and possibly fix the issue for you.

**Comment by Lumaah** [comment]
[Tord Red Fury - Leader (Lumaah) [Tord Rework].zip](https://github.com/accountrev/funkychart/files/9638386/Tord.Red.Fury.-.Leader.Lumaah.Tord.Rework.zip)

**Comment by IlasTv** [comment]
^ i have the same issue, the down note just doesn't load

**Comment by accountrev** [comment]
Hello, sorry for the very late reply.
I will be pushing a new update today that fixes this issue + some other bugs from the GUI side.
For now (so you don't have to wait) please replace the data from the chart that you converted with the one I will leave attached here.
You will need to replace some things inside the lua file, like the audio name and such, but the version I will send you has the down arrow added. Thank you!
[TordRedFuryFixed_111111111.1.lua.zip](https://github.com/accountrev/funkychart/files/9740095/TordRedFuryFixed_111111111.1.lua.zip)
