### ISSUE TITLE
error while try running with script

### ISSUE THREAD

**Issue by adgods1** [accountrev/funkychart#5]
![image](https://user-images.githubusercontent.com/98714456/162545625-b4ad12eb-6774-490f-af94-6960efefd8c9.png)

**Comment by accountrev** [comment]
Thanks for reporting these errors.
Can you tell me how you got them to appear? Was it when you loaded the chart? When you pressed Play Chart? While playing?

**Comment by adgods1** [comment]
no am just dumb

**Comment by adgods1** [comment]
sorry

**Comment by accountrev** [comment]
What was the problem before I close this issue? Just curious.

**Comment by adgods1** [comment]
![image](https://user-images.githubusercontent.com/98714456/162547961-cc86f5f1-d94d-45da-95e6-012b9898cb83.png)
pasted this

**Comment by accountrev** [comment]
You aren't supposed to be opening that file. You should be loading it through the GUI. Watch the tutorial to find out more.
