### ISSUE TITLE
So i have a issue when i load a song its just stuck at 00:00 how do i fix this problem and why does it appear like this?

### ISSUE THREAD

**Issue by ymyfalts** [accountrev/funkychart#6]
![86b59146b27f583246b228ad9983b4c7](https://user-images.githubusercontent.com/102472301/162562210-c6d1b237-98e0-4bee-8ef2-bf02b36efd49.png)

**Comment by ymyfalts** [comment]
![4f9859064d87a5e6d3b67b9228622476](https://user-images.githubusercontent.com/102472301/162563271-64aacd57-d5d0-4c44-8fd2-698b8be81658.png)

**Comment by ymyfalts** [comment]
I got that from console of a error audio thing

**Comment by accountrev** [comment]
I pushed an update just now, you just need to select your executor when you load a chart. Tell me if this changes anything.

**Comment by ymyfalts** [comment]
Its now fixed, Thank you!

**Comment by RobloxDead** [comment]
> I pushed an update just now, you just need to select your executor when you load a chart. Tell me if this changes anything.

how to select executor

**Comment by Errorsansiguess** [comment]
you have to get the new update and then and under the load chart you will see executer have to hit the arrow to the left of it and choose krnl if you are using krnl but choose synapse if you are using synapse

**Comment by accountrev** [comment]
> Its now fixed, Thank you!

👍
