### ISSUE TITLE
My audio is in the audio file but says it's missing.

### ISSUE THREAD

**Issue by PriestlyFlea** [accountrev/funkychart#7]
![image](https://user-images.githubusercontent.com/103327350/162582852-499cdbca-33a9-4bc0-9419-d5267fbf749b.png)
![image](https://user-images.githubusercontent.com/103327350/162582896-10c07043-3112-48ab-b0d2-4f6b4462a0ff.png)
What do I do. The audio is in the audio file and I followed the steps.

**Comment by accountrev** [comment]
I pushed an update just now, but this error happens with Synapse X if you rejoin the game.
You just need to reload the chart and it should fix it.
