### ISSUE TITLE
The converter doesn't output a chart

### ISSUE THREAD

**Issue by GameGuyOnYT** [accountrev/funkychart#8]
Hello, I'm trying to covert a chart of the song Feelin' Sky but it doesn't appear in the destination folder. The audio appears but the chart doesn't. I put a video of me showing this error below and you can find the chart [here](https://mega.nz/file/8GhE0JbY#3p0KsmHRAJELI6H1WzKnr7ZcGyTyWaqu5GDzFjS5N8U). Help would be appreciated.

[Video](https://user-images.githubusercontent.com/81768350/162584499-9bb9b851-00c6-41e1-b8e4-6723d23f47f6.mp4)

**Comment by accountrev** [comment]
Thanks for finding this error. This is an issue with the converter, will be fixing this next update (v2.0).
